# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connect.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rconnect.proto\x12\x07\x63onnect\"\"\n\nInitialize\x12\x14\n\x0cinit_message\x18\x01 \x01(\t\"&\n\tFrequency\x12\x19\n\x11\x63ycles_per_second\x18\x01 \x01(\x01\"\x17\n\x05Phase\x12\x0e\n\x06number\x18\x01 \x01(\x01\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"/\n\x0cGraphSamples\x12\x1f\n\x07samples\x18\x01 \x03(\x0b\x32\x0e.connect.Point2\xbe\x01\n\nConnection\x12<\n\x0eInitialization\x12\x13.connect.Initialize\x1a\x15.connect.GraphSamples\x12<\n\x0f\x46requencyChange\x12\x12.connect.Frequency\x1a\x15.connect.GraphSamples\x12\x34\n\x0bPhaseChange\x12\x0e.connect.Phase\x1a\x15.connect.GraphSamplesB\x19\xaa\x02\x16ImplantedDeviceServiceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connect_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\026ImplantedDeviceService'
  _INITIALIZE._serialized_start=26
  _INITIALIZE._serialized_end=60
  _FREQUENCY._serialized_start=62
  _FREQUENCY._serialized_end=100
  _PHASE._serialized_start=102
  _PHASE._serialized_end=125
  _POINT._serialized_start=127
  _POINT._serialized_end=156
  _GRAPHSAMPLES._serialized_start=158
  _GRAPHSAMPLES._serialized_end=205
  _CONNECTION._serialized_start=208
  _CONNECTION._serialized_end=398
# @@protoc_insertion_point(module_scope)
